Clock Page
mikuweb/Feel_Your_Achievement pull request #14
Opened 2023-05-04 03:37 UTC by mikuweb

TimerとStop watch機能を作成して、クリックしたボタンによってそれぞれ表示が切り替わるようにしました！確認お願いします。

2023-05-05 01:50 UTC, Doiverson requested changes

2023-05-05 01:50 UTC, Doiverson commented on pages/clock/index.tsx
> +            </div>
タブをクリックした時に下線が表示されることでちょっとだけ上下にズレるから、paddingかheightかを変えて調整するといいかも！

![Screen_Recording_2023-05-04_at_6_46_52_PM_AdobeExpress](https://user-images.githubusercontent.com/38961459/236362739-c08b5a2c-7e93-43a2-936f-1364c139e30a.gif)

2023-05-05 01:52 UTC, Doiverson commented
`Timer.tsx` と `StopWatch.tsx` は重複してるコードが結構あるから一つのコンポーネントにまとめられるとスッキリするかもな！（ここは気が向いたらやってもらったら大丈夫！）

基本的にはあまり重複したコードが複数ファイルにまたがって無いようにするといいコードになるよ✨

2023-05-05 01:54 UTC, Doiverson commented on components/Timer.tsx
`StopWatch.tsx` と重複してる箇所があるから確認してみるといいかも！

2023-05-05 09:53 UTC, mikuweb commented on pages/clock/index.tsx
> +            </div>
ありがとう！修正しました！

2023-05-05 09:54 UTC, mikuweb commented on components/Timer.tsx
ありがとう！Timer.tsx と StopWatch.tsxで重複してたところをPauseResumeBtn.tsxコンポーネントにまとめた！

2023-05-06 06:39 UTC, Doiverson approved these changes

2023-05-06 06:41 UTC, merged